### ISSUE TITLE
Update key/values within existing reader function or pass existing dictionary and create new function?

### ISSUE THREAD

**Issue by injectedfusion** [injectedfusion/dynamic_inventory_generator#4]
I am at crossroad where I'm not sure if I should attempt to create a dictionary within single function with the final key values that I want or if I should perform the updating of the dictionary key values in new function.

I started down this path in a branch https://github.com/injectedfusion/dynamic_inventory_generator/blob/dict_updates/parser.py

@nellshamrell Any thoughts of best practices, and how to proceed?

**Comment by nellshamrell** [comment]
Taking a look at this now :)

**Comment by nellshamrell** [comment]
Hello again!

Here is what I would do (I will try to get a prototype together as able this week).

I would have three functions: **read_file**, **site_names_map**, and **replace_site_names**.

## read_file(path_to_hosts_file)
This function takes a path to a hosts file on the user's workstation (i.e. /tmp/hosts) 
If that path leads to a valid file, it opens that file
(TODO for the future - validate the file's format)

For each line in the file, create a dictionary (**dict**)
Then parse the line - creating key value pairs in **dict** for
* ipv4_result
* device_result
* site_result
* unit_result
* host_result

Then add the **dict** value to an array called **output**
Return **output**

## site_names_map(path_to_map_file)
Takes a path to a mapping file on the user's workstation (i.e. mappings/sites.json)
(TODO for the future - validate the file's format)
Creates new dictionary (**dict**) of keys and values from sites map file
Removes duplicates from **dict** dictionary
Returns **dict** dictionary

## replace_site_names
Loop through output array returned from **read_file(path_to_hosts_file)**
For each member of the output array
Take the member's site_name value
Match it to the dictionary returned from  **site_names_map(path_to_map_file)**
Replace member.site_name value with the value of the matching key in the site_names_map dictionary
After looping is complete, return the modified output array

**Comment by nellshamrell** [comment]
Closing this, as this functionality was added in #8
